name: facebook/zstd/nightly
on:
  schedule:
  - cron: 0 0 * * *
  push:
    branches:
    - release
    - dev
    - master
jobs:
  regression-test:
    runs-on: ubuntu-latest
    container:
      image: fbopensource/zstd-circleci-primary:0.0.1
      options: --entrypoint /bin/bash
    env:
      CIRCLE_ARTIFACTS: "/tmp/circleci-artifacts"
      NVM_DIR: "/tmp/nvm"
    steps:
    - name: Manually compile glibc and set nodejs version
      run: |
        # Upgrading the Ubuntu version used in fbopensource/zstd-circleci-primary would avoid this.
        mkdir $NVM_DIR
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 20
        sudo ln -s /tmp/nvm/versions/node/v20.11.0/bin/node /usr/local/bin/node
        sudo apt-get update
        sudo apt-get install gawk patchelf bison
        cd /tmp
        curl -O https://ftp.gnu.org/gnu/glibc/glibc-2.28.tar.gz
        tar -zxf glibc-2.28.tar.gz
        mkdir glibc-2.28/build && cd glibc-2.28/build
        ../configure --prefix=/opt/glibc-2.28
        make -j 4
        sudo make install
        patchelf --set-interpreter /opt/glibc-2.28/lib/ld-linux-x86-64.so.2 --set-rpath /opt/glibc-2.28/lib/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/ /usr/local/bin/node
    - uses: actions/checkout@v4
    - uses: actions/cache@v3
      with:
        key: regression-cache-{{ checksum "tests/regression/data.c" }}-v0
        path: tests/regression/cache
        restore-keys: regression-cache-{{ checksum "tests/regression/data.c" }}-v0
    - uses: actions/upload-artifact@v4
      with:
        path: "/tmp/circleci-artifacts"
    - name: Regression Test
      run: |
        make -C programs zstd
        make -C tests/regression test
        mkdir -p $CIRCLE_ARTIFACTS
        ./tests/regression/test                     \
            --cache  tests/regression/cache         \
            --output $CIRCLE_ARTIFACTS/results.csv  \
            --zstd   programs/zstd
        echo "NOTE: The new results.csv is uploaded as an artifact to this job"
        echo "      If this fails, go to the Artifacts pane in CircleCI, "
        echo "      download /tmp/circleci-artifacts/results.csv, and if they "
        echo "      are still good, copy it into the repo and commit it."
        echo "> diff tests/regression/results.csv $CIRCLE_ARTIFACTS/results.csv"
        diff tests/regression/results.csv $CIRCLE_ARTIFACTS/results.csv

# Longer tests
  #- make -C tests test-zstd-nolegacy && make clean
  #- pyenv global 3.4.4; make -C tests versionsTest && make clean
  #- make zlibwrapper         && make clean
  #- gcc -v; make -C tests test32 MOREFLAGS="-I/usr/include/x86_64-linux-gnu" && make clean
  #- make uasan               && make clean
  #- make asan32              && make clean
  #- make -C tests test32 CC=clang MOREFLAGS="-g -fsanitize=address -I/usr/include/x86_64-linux-gnu"
# Valgrind tests
  #- CFLAGS="-O1 -g" make -C zlibWrapper valgrindTest && make clean
  #- make -C tests valgrindTest && make clean
# ARM, AArch64, PowerPC, PowerPC64 tests
  #- make ppctest             && make clean
  #- make ppc64test           && make clean
  #- make armtest             && make clean
  #- make aarch64test         && make clean
